// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: titancompute.proto

package titancompute

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client request for inference
type InferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature   float32                `protobuf:"fixed32,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,6,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceRequest) Reset() {
	*x = InferenceRequest{}
	mi := &file_titancompute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceRequest) ProtoMessage() {}

func (x *InferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_titancompute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceRequest.ProtoReflect.Descriptor instead.
func (*InferenceRequest) Descriptor() ([]byte, []int) {
	return file_titancompute_proto_rawDescGZIP(), []int{0}
}

func (x *InferenceRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *InferenceRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *InferenceRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *InferenceRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *InferenceRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *InferenceRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// Coordinator response with agent endpoint
type InferenceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentEndpoint  string                 `protobuf:"bytes,1,opt,name=agent_endpoint,json=agentEndpoint,proto3" json:"agent_endpoint,omitempty"`
	SessionToken   string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	ExpiresAt      int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	JobId          string                 `protobuf:"bytes,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	EstimatedRttMs float64                `protobuf:"fixed64,5,opt,name=estimated_rtt_ms,json=estimatedRttMs,proto3" json:"estimated_rtt_ms,omitempty"`
	AgentId        string                 `protobuf:"bytes,6,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InferenceResponse) Reset() {
	*x = InferenceResponse{}
	mi := &file_titancompute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceResponse) ProtoMessage() {}

func (x *InferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titancompute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceResponse.ProtoReflect.Descriptor instead.
func (*InferenceResponse) Descriptor() ([]byte, []int) {
	return file_titancompute_proto_rawDescGZIP(), []int{1}
}

func (x *InferenceResponse) GetAgentEndpoint() string {
	if x != nil {
		return x.AgentEndpoint
	}
	return ""
}

func (x *InferenceResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *InferenceResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *InferenceResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *InferenceResponse) GetEstimatedRttMs() float64 {
	if x != nil {
		return x.EstimatedRttMs
	}
	return 0
}

func (x *InferenceResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// Agent registration on startup
type AgentRegistration struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Endpoint        string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	TotalVramMb     int64                  `protobuf:"varint,3,opt,name=total_vram_mb,json=totalVramMb,proto3" json:"total_vram_mb,omitempty"`
	TotalRamMb      int64                  `protobuf:"varint,4,opt,name=total_ram_mb,json=totalRamMb,proto3" json:"total_ram_mb,omitempty"`
	MaxJobs         int32                  `protobuf:"varint,5,opt,name=max_jobs,json=maxJobs,proto3" json:"max_jobs,omitempty"`
	SupportedModels []string               `protobuf:"bytes,6,rep,name=supported_models,json=supportedModels,proto3" json:"supported_models,omitempty"`
	Capabilities    map[string]string      `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentRegistration) Reset() {
	*x = AgentRegistration{}
	mi := &file_titancompute_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegistration) ProtoMessage() {}

func (x *AgentRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_titancompute_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegistration.ProtoReflect.Descriptor instead.
func (*AgentRegistration) Descriptor() ([]byte, []int) {
	return file_titancompute_proto_rawDescGZIP(), []int{2}
}

func (x *AgentRegistration) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentRegistration) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *AgentRegistration) GetTotalVramMb() int64 {
	if x != nil {
		return x.TotalVramMb
	}
	return 0
}

func (x *AgentRegistration) GetTotalRamMb() int64 {
	if x != nil {
		return x.TotalRamMb
	}
	return 0
}

func (x *AgentRegistration) GetMaxJobs() int32 {
	if x != nil {
		return x.MaxJobs
	}
	return 0
}

func (x *AgentRegistration) GetSupportedModels() []string {
	if x != nil {
		return x.SupportedModels
	}
	return nil
}

func (x *AgentRegistration) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegistrationResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Status                   string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message                  string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,3,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_titancompute_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titancompute_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_titancompute_proto_rawDescGZIP(), []int{3}
}

func (x *RegistrationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegistrationResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

// Periodic health updates from agents
type HealthUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	FreeVramMb    int64                  `protobuf:"varint,2,opt,name=free_vram_mb,json=freeVramMb,proto3" json:"free_vram_mb,omitempty"`
	FreeRamMb     int64                  `protobuf:"varint,3,opt,name=free_ram_mb,json=freeRamMb,proto3" json:"free_ram_mb,omitempty"`
	RunningJobs   int32                  `protobuf:"varint,4,opt,name=running_jobs,json=runningJobs,proto3" json:"running_jobs,omitempty"`
	QueuedJobs    int32                  `protobuf:"varint,5,opt,name=queued_jobs,json=queuedJobs,proto3" json:"queued_jobs,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,6,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	RttMs         float64                `protobuf:"fixed64,7,opt,name=rtt_ms,json=rttMs,proto3" json:"rtt_ms,omitempty"`
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthUpdate) Reset() {
	*x = HealthUpdate{}
	mi := &file_titancompute_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthUpdate) ProtoMessage() {}

func (x *HealthUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_titancompute_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthUpdate.ProtoReflect.Descriptor instead.
func (*HealthUpdate) Descriptor() ([]byte, []int) {
	return file_titancompute_proto_rawDescGZIP(), []int{4}
}

func (x *HealthUpdate) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HealthUpdate) GetFreeVramMb() int64 {
	if x != nil {
		return x.FreeVramMb
	}
	return 0
}

func (x *HealthUpdate) GetFreeRamMb() int64 {
	if x != nil {
		return x.FreeRamMb
	}
	return 0
}

func (x *HealthUpdate) GetRunningJobs() int32 {
	if x != nil {
		return x.RunningJobs
	}
	return 0
}

func (x *HealthUpdate) GetQueuedJobs() int32 {
	if x != nil {
		return x.QueuedJobs
	}
	return 0
}

func (x *HealthUpdate) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *HealthUpdate) GetRttMs() float64 {
	if x != nil {
		return x.RttMs
	}
	return 0
}

func (x *HealthUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HealthAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthAck) Reset() {
	*x = HealthAck{}
	mi := &file_titancompute_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthAck) ProtoMessage() {}

func (x *HealthAck) ProtoReflect() protoreflect.Message {
	mi := &file_titancompute_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthAck.ProtoReflect.Descriptor instead.
func (*HealthAck) Descriptor() ([]byte, []int) {
	return file_titancompute_proto_rawDescGZIP(), []int{5}
}

func (x *HealthAck) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HealthAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// System status queries
type StatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeAgents  bool                   `protobuf:"varint,1,opt,name=include_agents,json=includeAgents,proto3" json:"include_agents,omitempty"`
	IncludeMetrics bool                   `protobuf:"varint,2,opt,name=include_metrics,json=includeMetrics,proto3" json:"include_metrics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_titancompute_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_titancompute_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_titancompute_proto_rawDescGZIP(), []int{6}
}

func (x *StatusRequest) GetIncludeAgents() bool {
	if x != nil {
		return x.IncludeAgents
	}
	return false
}

func (x *StatusRequest) GetIncludeMetrics() bool {
	if x != nil {
		return x.IncludeMetrics
	}
	return false
}

type SystemStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalAgents   int32                  `protobuf:"varint,1,opt,name=total_agents,json=totalAgents,proto3" json:"total_agents,omitempty"`
	HealthyAgents int32                  `protobuf:"varint,2,opt,name=healthy_agents,json=healthyAgents,proto3" json:"healthy_agents,omitempty"`
	TotalJobs     int32                  `protobuf:"varint,3,opt,name=total_jobs,json=totalJobs,proto3" json:"total_jobs,omitempty"`
	Uptime        string                 `protobuf:"bytes,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Agents        []*AgentStatus         `protobuf:"bytes,5,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemStatus) Reset() {
	*x = SystemStatus{}
	mi := &file_titancompute_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatus) ProtoMessage() {}

func (x *SystemStatus) ProtoReflect() protoreflect.Message {
	mi := &file_titancompute_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatus.ProtoReflect.Descriptor instead.
func (*SystemStatus) Descriptor() ([]byte, []int) {
	return file_titancompute_proto_rawDescGZIP(), []int{7}
}

func (x *SystemStatus) GetTotalAgents() int32 {
	if x != nil {
		return x.TotalAgents
	}
	return 0
}

func (x *SystemStatus) GetHealthyAgents() int32 {
	if x != nil {
		return x.HealthyAgents
	}
	return 0
}

func (x *SystemStatus) GetTotalJobs() int32 {
	if x != nil {
		return x.TotalJobs
	}
	return 0
}

func (x *SystemStatus) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *SystemStatus) GetAgents() []*AgentStatus {
	if x != nil {
		return x.Agents
	}
	return nil
}

type AgentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	FreeVramMb    int64                  `protobuf:"varint,3,opt,name=free_vram_mb,json=freeVramMb,proto3" json:"free_vram_mb,omitempty"`
	RunningJobs   int32                  `protobuf:"varint,4,opt,name=running_jobs,json=runningJobs,proto3" json:"running_jobs,omitempty"`
	LastHeartbeat int64                  `protobuf:"varint,5,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_titancompute_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_titancompute_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_titancompute_proto_rawDescGZIP(), []int{8}
}

func (x *AgentStatus) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentStatus) GetFreeVramMb() int64 {
	if x != nil {
		return x.FreeVramMb
	}
	return 0
}

func (x *AgentStatus) GetRunningJobs() int32 {
	if x != nil {
		return x.RunningJobs
	}
	return 0
}

func (x *AgentStatus) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

// Direct streaming messages
type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature   float32                `protobuf:"fixed32,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Stream        bool                   `protobuf:"varint,6,opt,name=stream,proto3" json:"stream,omitempty"`
	Options       map[string]string      `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_titancompute_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_titancompute_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_titancompute_proto_rawDescGZIP(), []int{9}
}

func (x *StreamRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *StreamRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StreamRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *StreamRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *StreamRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *StreamRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *StreamRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_titancompute_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titancompute_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_titancompute_proto_rawDescGZIP(), []int{10}
}

func (x *StreamResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *StreamResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StreamResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *StreamResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *StreamResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *StreamResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Agent status requests
type AgentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	IncludeJobs   bool                   `protobuf:"varint,2,opt,name=include_jobs,json=includeJobs,proto3" json:"include_jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatusRequest) Reset() {
	*x = AgentStatusRequest{}
	mi := &file_titancompute_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusRequest) ProtoMessage() {}

func (x *AgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_titancompute_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusRequest.ProtoReflect.Descriptor instead.
func (*AgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_titancompute_proto_rawDescGZIP(), []int{11}
}

func (x *AgentStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentStatusRequest) GetIncludeJobs() bool {
	if x != nil {
		return x.IncludeJobs
	}
	return false
}

type AgentStatusResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	AgentId                string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status                 string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	FreeVramMb             int64                  `protobuf:"varint,3,opt,name=free_vram_mb,json=freeVramMb,proto3" json:"free_vram_mb,omitempty"`
	FreeRamMb              int64                  `protobuf:"varint,4,opt,name=free_ram_mb,json=freeRamMb,proto3" json:"free_ram_mb,omitempty"`
	ActiveSessions         int32                  `protobuf:"varint,5,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	TotalRequestsProcessed int64                  `protobuf:"varint,6,opt,name=total_requests_processed,json=totalRequestsProcessed,proto3" json:"total_requests_processed,omitempty"`
	ModelLoaded            string                 `protobuf:"bytes,7,opt,name=model_loaded,json=modelLoaded,proto3" json:"model_loaded,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AgentStatusResponse) Reset() {
	*x = AgentStatusResponse{}
	mi := &file_titancompute_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusResponse) ProtoMessage() {}

func (x *AgentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titancompute_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusResponse.ProtoReflect.Descriptor instead.
func (*AgentStatusResponse) Descriptor() ([]byte, []int) {
	return file_titancompute_proto_rawDescGZIP(), []int{12}
}

func (x *AgentStatusResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentStatusResponse) GetFreeVramMb() int64 {
	if x != nil {
		return x.FreeVramMb
	}
	return 0
}

func (x *AgentStatusResponse) GetFreeRamMb() int64 {
	if x != nil {
		return x.FreeRamMb
	}
	return 0
}

func (x *AgentStatusResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *AgentStatusResponse) GetTotalRequestsProcessed() int64 {
	if x != nil {
		return x.TotalRequestsProcessed
	}
	return 0
}

func (x *AgentStatusResponse) GetModelLoaded() string {
	if x != nil {
		return x.ModelLoaded
	}
	return ""
}

// Registration cleanup
type DeregistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregistrationRequest) Reset() {
	*x = DeregistrationRequest{}
	mi := &file_titancompute_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregistrationRequest) ProtoMessage() {}

func (x *DeregistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_titancompute_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregistrationRequest.ProtoReflect.Descriptor instead.
func (*DeregistrationRequest) Descriptor() ([]byte, []int) {
	return file_titancompute_proto_rawDescGZIP(), []int{13}
}

func (x *DeregistrationRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DeregistrationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeregistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregistrationResponse) Reset() {
	*x = DeregistrationResponse{}
	mi := &file_titancompute_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregistrationResponse) ProtoMessage() {}

func (x *DeregistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titancompute_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregistrationResponse.ProtoReflect.Descriptor instead.
func (*DeregistrationResponse) Descriptor() ([]byte, []int) {
	return file_titancompute_proto_rawDescGZIP(), []int{14}
}

func (x *DeregistrationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeregistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// JWT public key distribution
type PublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeyRequest) Reset() {
	*x = PublicKeyRequest{}
	mi := &file_titancompute_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyRequest) ProtoMessage() {}

func (x *PublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_titancompute_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyRequest.ProtoReflect.Descriptor instead.
func (*PublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_titancompute_proto_rawDescGZIP(), []int{15}
}

type PublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKeyPem  string                 `protobuf:"bytes,1,opt,name=public_key_pem,json=publicKeyPem,proto3" json:"public_key_pem,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Issuer        string                 `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeyResponse) Reset() {
	*x = PublicKeyResponse{}
	mi := &file_titancompute_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyResponse) ProtoMessage() {}

func (x *PublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_titancompute_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyResponse.ProtoReflect.Descriptor instead.
func (*PublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_titancompute_proto_rawDescGZIP(), []int{16}
}

func (x *PublicKeyResponse) GetPublicKeyPem() string {
	if x != nil {
		return x.PublicKeyPem
	}
	return ""
}

func (x *PublicKeyResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *PublicKeyResponse) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

var File_titancompute_proto protoreflect.FileDescriptor

const file_titancompute_proto_rawDesc = "" +
	"\n" +
	"\x12titancompute.proto\x12\x0ftitancompute.v1\"\xb0\x02\n" +
	"\x10InferenceRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x05 \x01(\x02R\vtemperature\x12Q\n" +
	"\n" +
	"parameters\x18\x06 \x03(\v21.titancompute.v1.InferenceRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x01\n" +
	"\x11InferenceResponse\x12%\n" +
	"\x0eagent_endpoint\x18\x01 \x01(\tR\ragentEndpoint\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x15\n" +
	"\x06job_id\x18\x04 \x01(\tR\x05jobId\x12(\n" +
	"\x10estimated_rtt_ms\x18\x05 \x01(\x01R\x0eestimatedRttMs\x12\x19\n" +
	"\bagent_id\x18\x06 \x01(\tR\aagentId\"\xf1\x02\n" +
	"\x11AgentRegistration\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\"\n" +
	"\rtotal_vram_mb\x18\x03 \x01(\x03R\vtotalVramMb\x12 \n" +
	"\ftotal_ram_mb\x18\x04 \x01(\x03R\n" +
	"totalRamMb\x12\x19\n" +
	"\bmax_jobs\x18\x05 \x01(\x05R\amaxJobs\x12)\n" +
	"\x10supported_models\x18\x06 \x03(\tR\x0fsupportedModels\x12X\n" +
	"\fcapabilities\x18\a \x03(\v24.titancompute.v1.AgentRegistration.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x01\n" +
	"\x14RegistrationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x03 \x01(\x05R\x18heartbeatIntervalSeconds\"\x85\x02\n" +
	"\fHealthUpdate\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12 \n" +
	"\ffree_vram_mb\x18\x02 \x01(\x03R\n" +
	"freeVramMb\x12\x1e\n" +
	"\vfree_ram_mb\x18\x03 \x01(\x03R\tfreeRamMb\x12!\n" +
	"\frunning_jobs\x18\x04 \x01(\x05R\vrunningJobs\x12\x1f\n" +
	"\vqueued_jobs\x18\x05 \x01(\x05R\n" +
	"queuedJobs\x12\x1f\n" +
	"\vcpu_percent\x18\x06 \x01(\x01R\n" +
	"cpuPercent\x12\x15\n" +
	"\x06rtt_ms\x18\a \x01(\x01R\x05rttMs\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"X\n" +
	"\tHealthAck\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"_\n" +
	"\rStatusRequest\x12%\n" +
	"\x0einclude_agents\x18\x01 \x01(\bR\rincludeAgents\x12'\n" +
	"\x0finclude_metrics\x18\x02 \x01(\bR\x0eincludeMetrics\"\xc5\x01\n" +
	"\fSystemStatus\x12!\n" +
	"\ftotal_agents\x18\x01 \x01(\x05R\vtotalAgents\x12%\n" +
	"\x0ehealthy_agents\x18\x02 \x01(\x05R\rhealthyAgents\x12\x1d\n" +
	"\n" +
	"total_jobs\x18\x03 \x01(\x05R\ttotalJobs\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\tR\x06uptime\x124\n" +
	"\x06agents\x18\x05 \x03(\v2\x1c.titancompute.v1.AgentStatusR\x06agents\"\xac\x01\n" +
	"\vAgentStatus\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12 \n" +
	"\ffree_vram_mb\x18\x03 \x01(\x03R\n" +
	"freeVramMb\x12!\n" +
	"\frunning_jobs\x18\x04 \x01(\x05R\vrunningJobs\x12%\n" +
	"\x0elast_heartbeat\x18\x05 \x01(\x03R\rlastHeartbeat\"\xbe\x02\n" +
	"\rStreamRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x05 \x01(\x02R\vtemperature\x12\x16\n" +
	"\x06stream\x18\x06 \x01(\bR\x06stream\x12E\n" +
	"\aoptions\x18\a \x03(\v2+.titancompute.v1.StreamRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x02\n" +
	"\x0eStreamResponse\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12I\n" +
	"\bmetadata\x18\x06 \x03(\v2-.titancompute.v1.StreamResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x12AgentStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12!\n" +
	"\finclude_jobs\x18\x02 \x01(\bR\vincludeJobs\"\x90\x02\n" +
	"\x13AgentStatusResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12 \n" +
	"\ffree_vram_mb\x18\x03 \x01(\x03R\n" +
	"freeVramMb\x12\x1e\n" +
	"\vfree_ram_mb\x18\x04 \x01(\x03R\tfreeRamMb\x12'\n" +
	"\x0factive_sessions\x18\x05 \x01(\x05R\x0eactiveSessions\x128\n" +
	"\x18total_requests_processed\x18\x06 \x01(\x03R\x16totalRequestsProcessed\x12!\n" +
	"\fmodel_loaded\x18\a \x01(\tR\vmodelLoaded\"J\n" +
	"\x15DeregistrationRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"J\n" +
	"\x16DeregistrationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x12\n" +
	"\x10PublicKeyRequest\"o\n" +
	"\x11PublicKeyResponse\x12$\n" +
	"\x0epublic_key_pem\x18\x01 \x01(\tR\fpublicKeyPem\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer2\xc5\x03\n" +
	"\x12CoordinatorService\x12Y\n" +
	"\x10RequestInference\x12!.titancompute.v1.InferenceRequest\x1a\".titancompute.v1.InferenceResponse\x12Z\n" +
	"\rRegisterAgent\x12\".titancompute.v1.AgentRegistration\x1a%.titancompute.v1.RegistrationResponse\x12M\n" +
	"\fReportHealth\x12\x1d.titancompute.v1.HealthUpdate\x1a\x1a.titancompute.v1.HealthAck(\x010\x01\x12R\n" +
	"\x11QuerySystemStatus\x12\x1e.titancompute.v1.StatusRequest\x1a\x1d.titancompute.v1.SystemStatus\x12U\n" +
	"\fGetPublicKey\x12!.titancompute.v1.PublicKeyRequest\x1a\".titancompute.v1.PublicKeyResponse2\xbc\x01\n" +
	"\fAgentService\x12T\n" +
	"\x0fStreamInference\x12\x1e.titancompute.v1.StreamRequest\x1a\x1f.titancompute.v1.StreamResponse0\x01\x12V\n" +
	"\tGetStatus\x12#.titancompute.v1.AgentStatusRequest\x1a$.titancompute.v1.AgentStatusResponseB3Z1github.com/titancompute/proto/gen/go;titancomputeb\x06proto3"

var (
	file_titancompute_proto_rawDescOnce sync.Once
	file_titancompute_proto_rawDescData []byte
)

func file_titancompute_proto_rawDescGZIP() []byte {
	file_titancompute_proto_rawDescOnce.Do(func() {
		file_titancompute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_titancompute_proto_rawDesc), len(file_titancompute_proto_rawDesc)))
	})
	return file_titancompute_proto_rawDescData
}

var file_titancompute_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_titancompute_proto_goTypes = []any{
	(*InferenceRequest)(nil),       // 0: titancompute.v1.InferenceRequest
	(*InferenceResponse)(nil),      // 1: titancompute.v1.InferenceResponse
	(*AgentRegistration)(nil),      // 2: titancompute.v1.AgentRegistration
	(*RegistrationResponse)(nil),   // 3: titancompute.v1.RegistrationResponse
	(*HealthUpdate)(nil),           // 4: titancompute.v1.HealthUpdate
	(*HealthAck)(nil),              // 5: titancompute.v1.HealthAck
	(*StatusRequest)(nil),          // 6: titancompute.v1.StatusRequest
	(*SystemStatus)(nil),           // 7: titancompute.v1.SystemStatus
	(*AgentStatus)(nil),            // 8: titancompute.v1.AgentStatus
	(*StreamRequest)(nil),          // 9: titancompute.v1.StreamRequest
	(*StreamResponse)(nil),         // 10: titancompute.v1.StreamResponse
	(*AgentStatusRequest)(nil),     // 11: titancompute.v1.AgentStatusRequest
	(*AgentStatusResponse)(nil),    // 12: titancompute.v1.AgentStatusResponse
	(*DeregistrationRequest)(nil),  // 13: titancompute.v1.DeregistrationRequest
	(*DeregistrationResponse)(nil), // 14: titancompute.v1.DeregistrationResponse
	(*PublicKeyRequest)(nil),       // 15: titancompute.v1.PublicKeyRequest
	(*PublicKeyResponse)(nil),      // 16: titancompute.v1.PublicKeyResponse
	nil,                            // 17: titancompute.v1.InferenceRequest.ParametersEntry
	nil,                            // 18: titancompute.v1.AgentRegistration.CapabilitiesEntry
	nil,                            // 19: titancompute.v1.StreamRequest.OptionsEntry
	nil,                            // 20: titancompute.v1.StreamResponse.MetadataEntry
}
var file_titancompute_proto_depIdxs = []int32{
	17, // 0: titancompute.v1.InferenceRequest.parameters:type_name -> titancompute.v1.InferenceRequest.ParametersEntry
	18, // 1: titancompute.v1.AgentRegistration.capabilities:type_name -> titancompute.v1.AgentRegistration.CapabilitiesEntry
	8,  // 2: titancompute.v1.SystemStatus.agents:type_name -> titancompute.v1.AgentStatus
	19, // 3: titancompute.v1.StreamRequest.options:type_name -> titancompute.v1.StreamRequest.OptionsEntry
	20, // 4: titancompute.v1.StreamResponse.metadata:type_name -> titancompute.v1.StreamResponse.MetadataEntry
	0,  // 5: titancompute.v1.CoordinatorService.RequestInference:input_type -> titancompute.v1.InferenceRequest
	2,  // 6: titancompute.v1.CoordinatorService.RegisterAgent:input_type -> titancompute.v1.AgentRegistration
	4,  // 7: titancompute.v1.CoordinatorService.ReportHealth:input_type -> titancompute.v1.HealthUpdate
	6,  // 8: titancompute.v1.CoordinatorService.QuerySystemStatus:input_type -> titancompute.v1.StatusRequest
	15, // 9: titancompute.v1.CoordinatorService.GetPublicKey:input_type -> titancompute.v1.PublicKeyRequest
	9,  // 10: titancompute.v1.AgentService.StreamInference:input_type -> titancompute.v1.StreamRequest
	11, // 11: titancompute.v1.AgentService.GetStatus:input_type -> titancompute.v1.AgentStatusRequest
	1,  // 12: titancompute.v1.CoordinatorService.RequestInference:output_type -> titancompute.v1.InferenceResponse
	3,  // 13: titancompute.v1.CoordinatorService.RegisterAgent:output_type -> titancompute.v1.RegistrationResponse
	5,  // 14: titancompute.v1.CoordinatorService.ReportHealth:output_type -> titancompute.v1.HealthAck
	7,  // 15: titancompute.v1.CoordinatorService.QuerySystemStatus:output_type -> titancompute.v1.SystemStatus
	16, // 16: titancompute.v1.CoordinatorService.GetPublicKey:output_type -> titancompute.v1.PublicKeyResponse
	10, // 17: titancompute.v1.AgentService.StreamInference:output_type -> titancompute.v1.StreamResponse
	12, // 18: titancompute.v1.AgentService.GetStatus:output_type -> titancompute.v1.AgentStatusResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_titancompute_proto_init() }
func file_titancompute_proto_init() {
	if File_titancompute_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_titancompute_proto_rawDesc), len(file_titancompute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_titancompute_proto_goTypes,
		DependencyIndexes: file_titancompute_proto_depIdxs,
		MessageInfos:      file_titancompute_proto_msgTypes,
	}.Build()
	File_titancompute_proto = out.File
	file_titancompute_proto_goTypes = nil
	file_titancompute_proto_depIdxs = nil
}
